name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy-to-aks:
    runs-on: linux-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Context
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        id: akscontext

      - name: Set Up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
        id: install

      - name: Get POD info
        run: kubectl get pods