name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Get POD info
        run: |
          export KUBECONFIG=${{ secrets.KUBECONFIG }}
          kubectl --version
          kubectl get pods