name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.2'
        id: install

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Get POD info
        run: |
          ls -la
          kubectl apply -f k8s/ngnix-deploy.yaml
          kubectl apply -f k8s/lb-svc.yaml
